GET http://localhost:3000/api/lista

###

POST http://localhost:3000/api/lista
Content-Type: application/json

{
    "title": "Minha nova tarefa"
}

###

GET http://localhost:3000/api/lista/1

###

PUT http://localhost:3000/api/lista/1
Content-Type: application/json

{
    "title": "Minha nova tarefa",
    "completed": true
}

###

DELETE http://localhost:3000/api/lista/1