

### Listar todos os produtos (Começa como um array vazio: [])
GET http://localhost:3000/api/produtos

###

### Criar um produto
POST http://localhost:3000/api/produtos
Content-Type: application/json

{
    "nome": "Chuteira de Campo",
    "descricao": "Trava alta para gramados naturais",
    "numeracao": 40
}


### Criar um produto
POST http://localhost:3000/api/produtos
Content-Type: application/json

{
    "nome": "Chuteira de Campo ",
    "descricao": "Trava baixa para gramas artificiais",
    "numeracao": 41
}

###

### Atualizar o produto criado (ID 1)
PUT http://localhost:3000/api/produtos/1
Content-Type: application/json

{
    "nome": "Chuteira Profissional",
    "descricao": "Trava alta com amortecimento",
    "numeracao": 40
}

###

### Deletar o produto (ID 1)
DELETE http://localhost:3000/api/produtos/1